initialization
initializeNatoDictionary
	"comment stating purpose of class-side method"

	"scope: class-variables  &  class-instance-variables"

	NatoDictionary := Dictionary new.
	NatoDictionary
		at: $a put: 'Alfa';
		at: $b put: 'Bravo';
		at: $c put: 'Charlie';
		at: $d put: 'Delta';
		at: $e put: 'Echo';
		at: $f put: 'Foxtrot';
		at: $g put: 'Golf';
		at: $h put: 'Hotel';
		at: $i put: 'India';
		at: $j put: 'Juliett';
		at: $k put: 'Kilo';
		at: $l put: 'Lima';
		at: $m put: 'Mike';
		at: $n put: 'November';
		at: $o put: 'Oscar';
		at: $p put: 'Papa';
		at: $q put: 'Quebec';
		at: $r put: 'Romeo';
		at: $s put: 'Sierra';
		at: $t put: 'Tango';
		at: $u put: 'Uniform';
		at: $v put: 'Victor';
		at: $w put: 'Whiskey';
		at: $x put: 'Xray';
		at: $y put: 'Yankee';
		at: $z put: 'Zulu';
		at: Character space put: '(space)';
		at: $1 put: 'One';
		at: $2 put: 'Two';
		at: $3 put: 'Three';
		at: $4 put: 'Four';
		at: $5 put: 'Five';
		at: $6 put: 'Six';
		at: $7 put: 'Seven';
		at: $8 put: 'Eight';
		at: $9 put: 'Nine';
		at: $0 put: 'Zero';
		yourself