SystemOrganization addCategory: #'DJW-Cassido Tests'!
SystemOrganization addCategory: #'DJW-Cassido Tests-DJW-Cassido 2020-5-4'!
SystemOrganization addCategory: #'DJW-Cassido Tests-DJW-Cassido-2020-05-11'!
SystemOrganization addCategory: #'DJW-Cassido Tests-DJW-Cassido-20200608'!
SystemOrganization addCategory: #'DJW-Cassido Tests-DJW-Cassido-20200622'!
SystemOrganization addCategory: #'DJW-Cassido Tests-DJW-Cassido-20200629'!
